#spring:
#  application:
#    name: MyProject
#  profiles:
#    active: aws
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/gathering
#    username: root
#    password: 0000
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: false
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: preejer8013@gmail.com
#    password: mvep okhv abar kkmx
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#server:
#  port: 80
#
#fcm:
#  firebase_config_path: firebase/gathering-project-dcf1a-firebase-adminsdk-fbsvc-061788000f.json
#
#jwt:
#  secretKey: Y2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
#  expiration: 3000
#
#file:
#  dir: C:/upload
